name: Laravel Deployment

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ðŸš€ NO COMPOSER INSTALL
      # ðŸš€ NO VENDOR UPLOAD

      - name: Deploy Code Only (FAST)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_TARGET }}/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/.env
            **/node_modules/**
            **/tests/**
            **/vendor/**
            storage/**
            bootstrap/cache/*.php
            **/*.md

      - name: Run Artisan Commands
        run: |
          curl -s -X POST \
          "https://backend.jonokollan.com/__deploy/run?key=${{ secrets.DEPLOY_KEY }}"
